
CREATE SCHEMA [Business]
GO

CREATE TABLE [Business].[Restaurant](
	Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	Name VARCHAR(50) NOT NULL DEFAULT '', 
	Description VARCHAR(50) NOT NULL DEFAULT '', 
	MainImageUrl VARCHAR(50) NOT NULL DEFAULT ''
)
GO